import "server-only";
import { cache } from "react";
import type { Firestore } from "firebase-admin/firestore";
import type { CategorySlug } from "./categories";
import type { Book, MediaEntry, Writing } from "./types";
import { MOCK_BOOKS, MOCK_MEDIA, MOCK_WRITINGS } from "./mock-data";

function hasAdminCredentials() {
  return Boolean(
    process.env.FIREBASE_PROJECT_ID &&
      process.env.FIREBASE_CLIENT_EMAIL &&
      process.env.FIREBASE_PRIVATE_KEY
  );
}

/**
 * Until a real Firebase project is connected (see README), every read below
 * falls back to local mock data so the site is fully browsable in dev/preview.
 * Once FIREBASE_* env vars are set, it reads from Firestore via the Admin SDK.
 */
async function withAdmin<T>(fallback: T, fn: (db: Firestore) => Promise<T>): Promise<T> {
  if (!hasAdminCredentials()) return fallback;
  const { getAdminDb } = await import("./firebase/admin");
  try {
    return await fn(getAdminDb());
  } catch (err) {
    console.error("Firestore read failed, falling back to mock data:", err);
    return fallback;
  }
}

/**
 * Wrapped in React's cache() so generateMetadata and the page component
 * (which often need the same data) share one Firestore read per request
 * instead of fetching twice.
 */
export const getLatestDaily = cache(async (): Promise<Writing | null> => {
  const fallback = MOCK_WRITINGS.filter((w) => w.category === "daily").sort((a, b) =>
    b.publishedAt.localeCompare(a.publishedAt)
  )[0] ?? null;

  return withAdmin(fallback, async (db) => {
    const snap = await db
      .collection("writings")
      .where("category", "==", "daily")
      .orderBy("publishedAt", "desc")
      .limit(1)
      .get();
    if (snap.empty) return fallback;
    return { id: snap.docs[0].id, ...snap.docs[0].data() } as Writing;
  });
});

export const getArchive = cache(async (category: CategorySlug): Promise<Writing[]> => {
  const fallback = MOCK_WRITINGS.filter((w) => w.category === category).sort((a, b) =>
    b.publishedAt.localeCompare(a.publishedAt)
  );

  return withAdmin(fallback, async (db) => {
    const snap = await db
      .collection("writings")
      .where("category", "==", category)
      .orderBy("publishedAt", "desc")
      .get();
    if (snap.empty) return fallback;
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }) as Writing);
  });
});

export const getWriting = cache(async (id: string): Promise<Writing | null> => {
  const fallback = MOCK_WRITINGS.find((w) => w.id === id) ?? null;

  return withAdmin(fallback, async (db) => {
    const doc = await db.collection("writings").doc(id).get();
    if (!doc.exists) return fallback;
    return { id: doc.id, ...doc.data() } as Writing;
  });
});

export const getTopics = cache(async (category: CategorySlug): Promise<string[]> => {
  const all = await getArchive(category);
  return Array.from(new Set(all.map((w) => w.topic).filter((t): t is string => Boolean(t)))).sort();
});

export const getByTopic = cache(async (category: CategorySlug, topic: string): Promise<Writing[]> => {
  const all = await getArchive(category);
  return all.filter((w) => w.topic === topic);
});

export const getRecentWritings = cache(async (max: number): Promise<Writing[]> => {
  const fallback = [...MOCK_WRITINGS]
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt))
    .slice(0, max);

  return withAdmin(fallback, async (db) => {
    const snap = await db.collection("writings").orderBy("publishedAt", "desc").limit(max).get();
    if (snap.empty) return fallback;
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }) as Writing);
  });
});

export const getAllWritings = cache(async (): Promise<Writing[]> => {
  const fallback = [...MOCK_WRITINGS].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));

  return withAdmin(fallback, async (db) => {
    const snap = await db.collection("writings").orderBy("publishedAt", "desc").get();
    if (snap.empty) return fallback;
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }) as Writing);
  });
});

export const getMedia = cache(async (): Promise<MediaEntry[]> => {
  const fallback = [...MOCK_MEDIA].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));

  return withAdmin(fallback, async (db) => {
    const snap = await db.collection("media").orderBy("publishedAt", "desc").get();
    if (snap.empty) return fallback;
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }) as MediaEntry);
  });
});

// Books are generated by scripts/generate-books.mjs, not authored via the
// portal, so unlike Writing/MediaEntry there's no create/update path here.
export const getBooks = cache(async (): Promise<Book[]> => {
  const fallback = [...MOCK_BOOKS].sort((a, b) => a.order - b.order);

  return withAdmin(fallback, async (db) => {
    const snap = await db.collection("books").orderBy("order", "asc").get();
    if (snap.empty) return fallback;
    return snap.docs.map((d) => ({ id: d.id, ...d.data() }) as Book);
  });
});
