import type { CategorySlug } from "./categories";

export interface Writing {
  id: string;
  category: CategorySlug;
  /** Absent for categories where hasTitle is false (e.g. daily — the text itself is the entry). */
  title?: string;
  /** HTML (from the portal's rich editor) for "rich" categories, plain text (line breaks preserved) for "plain" ones. */
  body: string;
  topic?: string;
  language: "ta" | "en";
  coverImageUrl?: string;
  audioUrl?: string;
  /** Daily-only: whether the author has selected this entry for the next book compilation (see scripts/generate-books.mjs). */
  bookIncluded?: boolean;
  publishedAt: string; // ISO date
  createdAt: string; // ISO datetime
}

export type NarrationStatus = "pending" | "recorded" | "approved";

/**
 * A daily haiku the author has flagged to read aloud himself. Doc id equals
 * the source Writing's id (one narration per haiku, at most). Lives in its
 * own Firestore collection until approved, at which point a real Writing is
 * created under the "naganavai" category and this record's status flips to
 * "approved".
 */
export interface Narration {
  id: string;
  text: string;
  sourcePublishedAt: string;
  status: NarrationStatus;
  audioUrl?: string;
  createdAt: string;
  publishedWritingId?: string;
}

/**
 * An entry on the /books (வானம்பாடி) page. Two kinds share the collection:
 * - "compilation": a PDF volume of குறிஞ்சிட்டு entries, generated by
 *   scripts/generate-books.mjs, not authored via the portal.
 * - "published": one of the author's real, independently-published books,
 *   added manually (cover image + title only, no PDF).
 */
export interface Book {
  id: string;
  order: number;
  kind: "compilation" | "published";
  /** Compilation: volume label, e.g. "தொகுப்பு 1". Published: author byline. */
  title: string;
  /** Compilation: shared series title, e.g. "சிந்தித்து பாருங்கள்". Published: the book's own title. */
  tamilTitle: string;
  /** Published books only: the real cover art. */
  coverImageUrl?: string;
  /** Compilation only, below. */
  haikuCount?: number;
  pdfUrl?: string;
  pdfSizeBytes?: number;
  generatedAt?: string; // ISO datetime
}

export type MediaKind = "podcast" | "video";

export interface MediaEntry {
  id: string;
  kind: MediaKind;
  title: string;
  description?: string;
  url: string;
  publishedAt: string; // ISO date
}

/** A photo in the தேன் குருவி gallery — memorable moments from the author's life, portal-authored. */
export interface GalleryPhoto {
  id: string;
  imageUrl: string;
  caption: string;
  publishedAt: string; // ISO date
}
